name: E2E Tests
on:
    push:
        branches-ignore:
            - 'main-built'

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        env:
            WP_BASE_URL: 'http://localhost:8888'
            WP_USERNAME: 'admin'
            WP_PASSWORD: 'password'
            WP_AUTH_STORAGE: '.auth/wordpress.json'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.11'

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup composer
              uses: php-actions/composer@v6
              with:
                  php_version: '8.3'
                  dev: no

            - name: Install packages
              run: yarn install --immutable

            - name: Build packages
              run: yarn build

            - name: Playwright install
              run: yarn playwright install chromium

            - name: Start wp-env
              run: yarn wp-env

            - name: Run Playwright tests
              run: npx playwright test --reporter=list

            - uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
