name: JS lint & test
on:
    push:
        branches:
            - '*'
            - '!main-built'

jobs:
    build:
        name: Lint & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11

            - name: Install packages
              run: yarn install --immutable

            - name: JS lint
              run: yarn lint:js

            - name: JS test
              run: yarn test:js
