name: JS lint & test
on:
    push:
        branches-ignore:
            - 'main-built'

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11

            - name: Install packages
              run: yarn install --immutable

            - name: JS lint
              run: yarn lint:js

            - name: JS test
              run: yarn test:js

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: js-report
                  path: js-report/
                  retention-days: 30
