name: PHP lint & test
on:
    push:
        branches-ignore:
            - 'main-built'

jobs:
    lint-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.11'
                  cache: 'yarn'

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup composer
              uses: php-actions/composer@v6
              with:
                  php_version: '8.3'

            - name: Install wp-env
              run: yarn add @wordpress/env

            - name: Validate Composer
              run: composer validate --strict

            - name: PHP Lint
              run: composer lint

            - name: PHPStan
              run: composer phpstan

            - name: PHPMD
              run: composer phpmd

            - name: Start wp-env
              run: yarn wp-env

            - name: WordPress unit test
              run: yarn php:unit

            - name: Debug Shell
              if: always()
              run: |
                  echo "Entering interactive shell for debugging"
                  bash
                  pwd
                  ls -la

            - name: WordPress integration test
              run: yarn php:integration

            - name: WordPress integration test as multisite
              run: yarn php:multisite

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: php-report
                  path: php-report/
                  retention-days: 30
