name: PHP lint & test
on:
    push:
        branches-ignore:
            - 'main-built'

jobs:
    lint-test:
        name: ${{ matrix.php-versions }} Lint & Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.3']

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2

            - name: Validate Composer
              run: composer validate --strict

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: PHP Lint
              run: composer lint

            - name: PHPStan
              run: composer phpstan

            - name: PHPMD
              run: composer phpmd

            - name: WordPress unit test
              run: composer test:unit
