name: Playwright Tests
on: [push]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            WP_BASE_URL: 'http://localhost:8888'
            WP_USERNAME: 'admin'
            WP_PASSWORD: 'password'
            WP_AUTH_STORAGE: '.auth/wordpress.json'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.11'

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup composer
              uses: php-actions/composer@v6
              with:
                  php_version: ${{ matrix.php-versions }}
                  command: update

            - name: Install packages
              run: yarn install --immutable

            - name: Start wp-env
              run: yarn wp-env

            - name: Run Playwright tests
              run: yarn test:e2e

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
