name: Build WordPress Plugin

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2

            - name: Install dependencies
              run: composer install --no-dev -o

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11

            - name: Install packages
              run: yarn install --immutable

            - name: JS build
              run: yarn build

            - name: Create and push built branch
              run: |
                  git checkout -b main-built
                  git add -A  # Stage all changes, including untracked files
                  git reset -- .husky/  # Unstage the .husky directory
                  git reset -- node_modules/  # Unstage the node_modules directory
                  git ls-files --ignored --exclude-standard -o -z | xargs -0 git rm --cached  # Remove ignored files from the index
                  git commit -m "Built WordPress plugin"
                  git push origin main-built
