name: Build WordPress Plugin

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2

            - name: Install dependencies
              run: composer install --no-dev -o

            - name: Deploy to main-built branch
              run: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
