name: Build WordPress Plugin

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2

            - name: Install dependencies
              run: composer install --no-dev -o

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11

            - name: Install packages
              run: yarn install --immutable

            - name: JS build
              run: yarn build

            - name: Apply deployignore
              run: |
                FILE=.deployignore
                if [ -f "$FILE" ]; then
                  cat .deployignore | xargs rm -rf
                fi

            - name: Push to built branch
              uses: Automattic/action-commit-to-branch@master
              with:
                  branch: 'main-built'
                  commit_message: 'Built plugin'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
